[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pages/index.html"
  status = 301

[[redirects]]
  from = "/home.html"
  to = "/pages/index.html"
  status = 301

[[redirects]]
  from = "/about.html"
  to = "/pages/about.html"
  status = 301

[[redirects]]
  from = "/cars.html"
  to = "/pages/cars.html"
  status = 301

[[redirects]]
  from = "/clothes.html"
  to = "/pages/clothes.html"
  status = 301

[[redirects]]
  from = "/scripts.html"
  to = "/pages/scripts.html"
  status = 301

[[redirects]]
  from = "/templates.html"
  to = "/pages/templates.html"
  status = 301

[[redirects]]
  from = "/admin.html"
  to = "/pages/admin.html"
  status = 301